# Generated by Django 4.1.7 on 2023-10-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_condition_place_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.type",
            ),
        ),
    ]
